AWSTemplateFormatVersion: 2010-09-09
Description: Fully working CFN Init + CFN HUP auto update demo

Parameters:
  WebContentVersion:
    Type: String
    Default: "v1"
    Description: Increase version number to trigger cfn-hup

Resources:

  DemoInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: !Sub |
                <h1>CloudFormation cfn-init & cfn-hup Demo</h1>
                <p>Updated Content Version: ${WebContentVersion}</p>
              mode: '000644'
              owner: root
              group: root

            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=2
              mode: '000400'
              owner: root
              group: root

            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.DemoInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource DemoInstance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: root
              group: root

          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf


    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c2b8ca1dad447f8a  # Amazon Linux 2 (modify if needed)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
            --stack ${AWS::StackName} \
            --resource DemoInstance \
            --region ${AWS::Region}

          /opt/aws/bin/cfn-signal -e $? \
            --stack ${AWS::StackName} \
            --resource DemoInstance \
            --region ${AWS::Region}

    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M